downstream_package_name: openscap
upstream_package_name: openscap
specfile_path: openscap.spec

actions:
  get-current-version:
  - bash -c "source release_tools/versions.sh && echo ${version}"

srpm_build_deps:
  - bash

jobs:
- job: copr_build
  trigger: pull_request
  identifier: standard
  targets:
  - fedora-all-x86_64
  - centos-stream-8-x86_64
  - centos-stream-9-x86_64

- job: tests
  trigger: pull_request
  identifier: standard-tests
  targets:
  - fedora-all-x86_64
  - centos-stream-8-x86_64
  - centos-stream-9-x86_64

- job: copr_build
  trigger: pull_request
  specfile_path: custom_specs/openscap_clang.spec
  identifier: clang
  targets:
  - epel-8-x86_64
  - epel-9-x86_64

- job: tests
  trigger: pull_request
  identifier: clang_tests
  skip_build: true
  targets:
  - epel-8-x86_64
  - epel-9-x86_64
