.TH OSCAP: "30" "Jun 2010" "Red Hat" "System Administration Utilities"

.SH NAME
oscap \- OpenSCAP command line tool

.SH SYNOPSIS
\fBoscap\fR [\fIgeneral-options\fR] \fBmodule\fR operation [\fIoperation-options-and-arguments\fR]

.SH DESCRIPTION
\fBoscap\fP is Security Content Automation Protocol (SCAP) toolkit based on OpenSCAP library. It provides various functions for 
different SCAP specifications(modules).

.SH GENERAL OPTIONS
.TP
\fB\-V, -\-version\fR
SCAP specification supported by the module.
.TP
\fB\-q, \-\-quiet\fR
No output for certain operations, only return code.
.TP
\fB\-h, \-\-help\fR
Help screen.

.SH MODULES
.TP
\fBoval\fR
Open Vulnerability and Assessment Language.
.TP
\fBxccdf\fR
The eXtensible Configuration Checklist Description Format.
.TP
\fBcvss\fR
Common Vulnerability Scoring System

.SH OVAL OPERATIONS
.TP
.B collect\fR oval-definitions-file
.RS
Probe the system and gather system characteristics for objects in OVAL Definition file. Print output (OVAL System Characteristic) to standart output.
.RE
.PP
.B eval\fR [\fIoptions\fR] oval-definitions-file
.RS
Probe the system and evaluate all definitions from OVAL Definition file. Print result of each definition to standard output. oscap returns 0 if all definitions pass. If there is an error during evaluation, the return code is 1. If there is at least one failed result definition, oscap-scan finishes with return code 2.
.PP
.TP
\fB\-\-result-file FILE\fR
.RS
Write OVAL Results into file.
.RE
.RE

.TP
.B eval-id\fR [--result-file FILE] --id definition-id oval-definitions-file
.RS
Probe the system and evaluate specified definition from OVAL Definition file. Print results of evaluation to standard output.
.RE

.TP
.B validate-xml\fR [\fIoptions\fR] oval-file
.RS
Validate given OVAL file against a XML schema. Every found error is printed to the standard output. Return code is 0 if validation succeeds, 1 if validation could not be performed due to some error, 2 if the OVAL document is not valid.
.TP
\fB\-\-version VER\fR
Specify version of the specification the document shall conform to.
.TP
\fB\-\-definitions\fR, \fB\-\-syschar\fR, \fB\-\-results\fR
Specify whether the validated document is an OVAL definitions file, OVAL system characteristics file, or OVAL results file. Default: definitions.

.RE
.B generate-report\fR  [\fIoptions\fR] oval-results-file
.RS
Generate a formatted HTML page containing visualisation of an OVAL results file. Unless the --output option is specified it will be written to the standard output.
.TP
\fB\-\-output FILE\fR
Write the report to this file instead of standard output.
.RE

.SH XCCDF OPERATIONS
.TP
.B eval\fR [\fIoptions\fR] xccdf-file [\fIoval-definitions-files\fR]
.RS
Perform evaluation driven by XCCDF file and use OVAL as checking engine. Print result of each rule to standard output. oscap returns 0 if all rules pass. If there is an error during evaluation, the return code is 1. If there is at least one failed rule, oscap-scan finishes with return code 2.
.PP
You should specify all required OVAL Definition files as last parameters.
.PP
.TP
\fB\-\-profile PROFILE\fR
.RS
Select profile from XCCDF document, otherwise the first profile is used.
.RE
.TP
\fB\-\-result-file FILE\fR
.RS
Write XCCDF results into file.
.RE
.TP
\fB\-\-report-file FILE\fR
Write HTML report into file. You also have to specify --result-file for this feature to work.
.RE
.RE
.TP
.B resolve\fR -o output-file xccdf-file
.RS
Resolve an XCCDF file as described in the XCCDF specification. It will flatten inheritance hierarchy of XCCDF profiles, groups, rules, and values. Result is another XCCDF document, which will be written to \fIoutput-file\fR.
.TP
\fB\-\-force\fR
Force resolving XCCDF document even if it is already marked as resolved.
.RE
.TP
.B validate-xml\fR [\fIoptions\fR] xccdf-file
.RS
Validate given XCCDF file against a XML schema. Every found error is printed to the standard output. Return code is 0 if validation succeeds, 1 if validation could not be performed due to some error, 2 if the XCCDF document is not valid.
.TP
\fB\-\-version VER\fR
Specify version of the specification the document shall conform to.
.RE
.TP
.B generate-report\fR  [\fIoptions\fR] --result-id id xccdf-file
.RS
Generate a formatted HTML page containing results of a XCCDF Benchmark execution. Unless the --output option is specified it will be written to the standard output. ID of the TestResult element to visualise must be provided.
.TP
\fB\-\-result-id ID\fR
ID of the XCCDF TestResult from which the report will be generated.
.TP
\fB\-\-output FILE\fR
Write the report to this file instead of standard output.
.RE

.SH CVSS OPERATIONS
.TP
.B base\fR \fImetrics\fR
.RS
Calculate base score from Access Vector (AV), Access Complexity (AC), Authentication(AU), Confidentiality Impact(CI),  Integrity Impact(II) and Availability Impact(AI) metric.
.RE
.PP
.B temporal\fR --base <num> [\fImetrics\fR]
.RS
Calculate temporal score from base score, Exploitability(EX), Remediation Level(RL) and Report Confidence(RC) metric.
.RE
.PP
.B environmental\fR \fImetrics\fR
.RS
Calculate environmental score from Collateral Damage Potential(CD), Target Distribution(TD), Confidentiality Requirement (CR),  Integrity Requirement(IR), Availability Requirement(AR),
Access Vector (AV), Access Complexity (AC), Authentication(AU), Confidentiality Impact(CI),  Integrity Impact(II), Availability Impact(AI), Exploitability(EX), Remediation Level(RL) and Report Confidence(RC) metric.
.RE
.PP
metrics:
.TP
\fB\-\-AV=\fR[local|adjacent-network|network] - Access Vector (required)
.TP
\fB\-\-AC=\fR[low|medium|high] - Access Complexity (required)
.TP
\fB\-\-AU=\fR[none|single|multiple] - Authentication (required)
.TP
\fB\-\-CI=\fR[none|partial|complete] - Confidentiality Impact (required)
.TP
\fB\-\-II=\fR[none|partial|complete] - Integrity Impact (required)
.TP
\fB\-\-AI=\fR[none|partial|complete] - Availability Impact (required)
.TP
\fB\-\-EX=\fR[unproven|proof-of-concept|functional|high|not-defined] - Exploitability
.TP
\fB\-\-RL=\fR[official-fix|temporary-fix|workaround|unavailable|not-defined] - Remediation Level
.TP
\fB\-\-RC=\fR[unconfirmed|uncorrporated|confirmed|not-defined] - Report Confidence
.TP
\fB\-\-CD=\fR[none|low|low-medium|medium-high|high|not-defined] - Collateral Damage Potential
.TP
\fB\-\-TD=\fR[none|low|medium|high|not-defined] - Target Distribution
.TP
\fB\-\-CR=\fR[low|medium|high|not-defined] - Confidentiality Requirement
.TP
\fB\-\-IR=\fR[low|medium|high|not-defined] - Integrity Requirement
.TP
\fB\-\-AR=\fR[low|medium|high|not-defined] - Availability Requirement


.SH CONTENT
.TP
\fB National Vulnerability Database\fR - \fIhttp://web.nvd.nist.gov/view/ncp/repository\fR
.TP
\fB Red Hat content repository\fR - \fIhttp://www.redhat.com/security/data/oval/\fR


.SH AUTHOR
Peter Vrabec <pvrabec@redhat.com>
