.TH oscap-chroot "8" "February 2016" "Red Hat, Inc." "System Administration Utilities"
.SH NAME
oscap-chroot \- Tool for offline SCAP evaluation of filesystems mounted at arbitrary paths.
.SH DESCRIPTION
oscap-chroot runs oscap tool on it in a filesystem mounted at given path.

Usage of the tool mimics usage and options of oscap(8) tool.

.SH USAGE
.SS Evaluation of XCCDF content
$ oscap-chroot CHROOT_PATH xccdf eval [options] INPUT_CONTENT

supported oscap xccdf eval options are:
  --profile
  --tailoring-file
  --tailoring-id
  --cpe (external OVAL dependencies are not supported yet!)
  --oval-results
  --sce-results
  --check-engine-results
  --results
  --results-arf
  --report
  --skip-valid
  --fetch-remote-resources
  --progress
  --datastream-id
  --xccdf-id
  --benchmark-id

.SS Evaluation of OVAL content
$ oscap-chroot image CHROOT_PATH oval eval [options] INPUT_CONTENT

supported oscap oval eval options are:
  --id
  --variables
  --directives
  --results
  --report
  --skip-valid
  --datastream-id
  --oval-id
  --probe-root

.SS Collection of OVAL System Characteristic
$ oscap-chroot CHROOT_PATH oval collect [options] INPUT_CONTENT

supported oscap oval collect options are:
  --id
  --syschar
  --variables
  --skip-valid


.SH REPORTING BUGS
.nf
Please report bugs using https://github.com/OpenSCAP/openscap/issues

.SH AUTHORS
.nf
Martin Preisler <mpreisle@redhat.com>
.fi
