.TH OSCAP_SCAN: "8" "Mar 2010" "Red Hat" "System Administration Utilities"
.SH NAME
oscap-scan \- Evaluate OVAL content
.SH SYNOPSIS
.B oscap-scan
.RB [ option ]\ [ XML_FILE|URL ]
.SH DESCRIPTION
\fBoscap-scan\fP will perform an evaluation of the system based on the
file given as input. The input source may be either the full path to
the xml file or an URL from which to download it. Currently, only
OVAL content is supported.

.SH OPTIONS
.TP
.B \-v
Run in verbose mode.
.TP
.B \-vv
Run in very verbose mode
.TP
.B \-o, \-\-objects only
evaluate objects only, ignore definitions and verbosity

.SH AUTHOR
Maros Barabas
