.TH OSCAP_SCAN: "8" "Mar 2010" "Red Hat" "System Administration Utilities"
.SH NAME
oscap-scan \- Evaluate OVAL content
.SH SYNOPSIS
.B oscap-scan
.RB [ option ]\ [ URL|file ]
.SH DESCRIPTION
\fBoscap-scan\fP will perform evaluation of the system based on the
OVAL definition \fBfile\fP. The input file may be found on disk or downloaded from a
given URL. 
.SH OPTIONS
.TP
\fB\-v, \-\-verbose\fR=\fIN\fR
increment verbosity level, one level for each -v found on the command line or 
specified by argument N of \fI--verbose\fR option.
.TP
.B \-q, \-\-quiet
quiet mode. Suppress all warning and messages
.TP
.B \-o, \-\-objects only
evaluate objects only, ignore definitions and verbosity 
.TP
\fB\-\-result-file FILE\fR
send OVAL results to FILE
.TP
\fB\-\-syschar-file FILE\fR
output system characteristic to separate file
.TP
.B \-h, \-\-help
display this help and exit
.SH RETURN VALUE
oscap-scan returns 0 if all definitions pass. If there is an error during evaluation, the return code is 1.  
If there is at least one failed result definition, oscap-scan finishes with return code 2.
.SH AUTHOR
Maros Barabas <mbarabas@redhat.com>
